### ISSUE TITLE
Document & provide example for custom pricing script

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/docs#102]
We've added to akash the ability to do custom bid pricing with an external script. The command line switch document how to set this up, but do not actually document the exact interface the script needs to implement. 

We need to

* Document the interface
* Document any data structures used
* Document any expectations around the script
* Provide a complete example script in a common scripting language e.g. python3

**Comment by Ropes** [comment]
https://chromium.googlesource.com/external/github.com/spf13/cobra/+/refs/heads/master/doc/md_docs.md <- Kubernetes uses this to generate docs. Might be a useful starting point?

**Comment by hydrogen18** [comment]
Done as part of @rsum1 's update
