### ISSUE TITLE
I believe this link is leading to "wrong" place

### ISSUE THREAD

**Issue by matsuro-hadouken** [ovrclk/docs#114]
**In documentation here** https://docs.akash.network/testnet-challenges/testnet-challenges/guided-deployments#challenge-2-week-2

**SDL** link leading in to **SDL** documentation: https://docs.akash.network/documentation/sdl

**Expected behavior:**

Lead do **deploy-2-2.yaml**
https://github.com/ovrclk/docs/blob/ac011af1802a7c5fc7bb90d979c4f4877eaa24e1/testnet-challenges/deploy-2-2.yaml

**Comment by musakov94** [comment]
make PR

**Comment by colinster** [comment]
Deprecated these pages in Docs.
