### ISSUE TITLE
creating validator returns out of gas message

### ISSUE THREAD

**Issue by wcdanh2** [ovrclk/docs#129]
When running "akash tx staking create-validator {...}" with --gas="auto" an out of gas error is returned.   Running the command without --gas="auto" succeeds.

-side note: the docs are not clear on how to get $VALIDATOR_ADDRESS for the section "View Validator Description"  per discord discussion it can be found in the return message of a successful create-validator command.

**Comment by hydrogen18** [comment]
Hello, please ask questions like this in the Akash Discord server. you can find that and our other community links here: 

https://akash.network/community/
