### ISSUE TITLE
Add a "report an issue" badge that links to the docs repo

### ISSUE THREAD

**Issue by boz** [ovrclk/docs#171]
So that people know that they can report issues, and they report it to the right place.

**Comment by dmikey** [comment]
There is an "Edit on Github" link, that takes a user directly to the page, they can make a change in the github ui, and then submit a PR. I wonder if they just get mixed up with "GitHub" in the navigation bar?

![Screen Shot 2021-05-13 at 8 29 22 AM](https://user-images.githubusercontent.com/328000/118132566-718e1c00-b3c5-11eb-9709-cbf7b5652236.png)
