### ISSUE TITLE
Improve instructions for bidding on Testnet as a Provider

### ISSUE THREAD

**Issue by ngehani** [ovrclk/docs#178]
dehazelabs.com are stuck on bidding as a Provider on Testnet. They aren't able to find instructions on how to do this. They have been stuck for a week.

The CEO of https://dehazelabs.com reached out on Discord and wants to be a provider and a tenant. This is the right kind of Provider we want to onboard early. Their timeline to go on Mainnet is ~4 weeks.

> “yeah we are not able to find any doc to be able to bid as a provider on the testnet.  Yeah we followed this and there were a lot of missing instructions. We have notes which I will share so you guys can update the docs. "

**Comment by colinster** [comment]
DeHaze Labs is now up and running on Testnet. The instructions are the same as Mainnet.
