### ISSUE TITLE
update usage docs with latest CLI chages

### ISSUE THREAD

**Issue by gosuri** [ovrclk/docs#30]
The below sections needs an update:

- [ ] [Query Network](https://docs.akash.network/usage/cli/query)
- [ ] [Send Tokens](https://docs.akash.network/usage/cli/send)
- [ ] [Get remote node status](https://docs.akash.network/usage/cli/status)

**Comment by anilCSE** [comment]
Fix 1 and 2:

**Comment by anilCSE** [comment]
Update PR https://github.com/ovrclk/docs/pull/31:
- [x] Query Network
- [x] Send Tokens
- [ ] Get remote node status
