### ISSUE TITLE
scrub: token unit

### ISSUE THREAD

**Issue by boz** [ovrclk/docs#92]
we used to use `u` to denote micro akash; that unit is no longer valid.  it should be `akash` always and everywhere.

**Comment by gosuri** [comment]
the correct branding for our token is AKT (and uAKT) please also be
cognizant to the fact we’ll be supporting multiple currencies in the future
(For BD efforts)
-- 
sent on mobile

**Comment by boz** [comment]
it supports multiple currencies but these docs show the syntax from when it didn't.
